call npm install gulp --save-dev
call npm install gulp-jshint --save-dev
call npm install gulp-changed --save-dev
call npm install gulp-concat --save-dev
call npm install gulp-strip-debug --save-dev
call npm install gulp-uglify --save-dev
call npm install gulp-karma --save-dev
call npm install karma-jasmine --save-dev
call npm install karma-phantomjs-launcher --save-dev